
USE EDW.EDW_STG;

CREATE OR REPLACE FILE FORMAT EDW_CSV_FRMT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '\042';



CREATE OR REPLACE STAGE HR_REGIONS_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_COUNTRIES_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_LOCATIONS_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_DEPARTMENTS_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_JOBS_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_EMPLOYEES_DATA FILE_FORMAT = EDW_CSV_FRMT;
CREATE OR REPLACE STAGE HR_JOB_HISTORY_DATA FILE_FORMAT = EDW_CSV_FRMT;


---Snowsql connect to snowflake edw_stg connection

		
snowsql -c edw_stg

--List the STAGE contents 

LIST @HR_REGIONS_DATA;  --Nothing as of now


--SnowSQL PUT Command(s) to push the Exported file(s) from Local to the STAGE(s) created above. Correct the DIRECTORY path according to your path to these scripts.
 
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_REGIONS.csv' @HR_REGIONS_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_COUNTRIES.csv' @HR_COUNTRIES_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_LOCATIONS.csv' @HR_LOCATIONS_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_DEPARTMENTS.csv' @HR_DEPARTMENTS_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_JOBS.csv' @HR_JOBS_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_EMPLOYEES.csv' @HR_EMPLOYEES_DATA;
PUT 'file://D:\\INYDZP\\Snowflake\\End to End Project\\Source Files\\HR_JOB_HISTORY.csv' @HR_JOB_HISTORY_DATA;


--Reference COPY Command(s) to Load Data (Using Task or pipe) into Staging tables by converting appropriate data types during the data load process.

--REGIONS LOAD 
COPY INTO EDW.EDW_STG.REGIONS 
    FROM
        (SELECT $1::NUMBER,$2::VARCHAR2(25),MD5($2::VARCHAR2(25)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_REGIONS_DATA);
		 
		 
--Create PIPE for REGIONS 

CREATE OR REPLACE PIPE STG_REGIONS_PP 
AS 
COPY INTO EDW.EDW_STG.REGIONS 
    FROM
        (SELECT $1::NUMBER,$2::VARCHAR2(25),MD5($2::VARCHAR2(25)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_REGIONS_DATA);
         
ALTER PIPE STG_REGIONS_PP   REFRESH;
		 
--COUNTRIES LOAD 
		 
COPY INTO EDW.EDW_STG.COUNTRIES 
    FROM
        (SELECT $1::CHAR(2),$2::VARCHAR2(40),$3::NUMBER,MD5($2||$3::VARCHAR2),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_COUNTRIES_DATA);

--LOCATIONS LOAD 

COPY INTO EDW.EDW_STG.LOCATIONS
    FROM
        (SELECT $1::NUMBER(4),$2::VARCHAR2(40),$3::VARCHAR2(12),$4::VARCHAR2(30),$5::VARCHAR2(25),$6::CHAR(2),MD5($2||$3||$4||$5||$6),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_LOCATIONS_DATA);


--DEPARTMENTS LOAD

COPY INTO EDW.EDW_STG.DEPARTMENTS 
    FROM
        (SELECT $1::NUMBER(4),$2::VARCHAR2(30),$3::NUMBER(6),$4::NUMBER(4),MD5($2||$3::VARCHAR2(6)||$4::VARCHAR2(4)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_DEPARTMENTS_DATA);
		 
--JOBS LOAD		

		 
COPY INTO EDW.EDW_STG.JOBS
    FROM
        (SELECT $1::VARCHAR2(10),$2::VARCHAR2(35),$3::NUMBER(6),$4::NUMBER(6),MD5($2||$3::VARCHAR2(6)||$4::VARCHAR2(6)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_JOBS_DATA);
		 
--EMPLOYEES LOAD 

COPY INTO  EDW.EDW_STG.EMPLOYEES
    FROM
        (SELECT $1::NUMBER(6),$2::VARCHAR2(20),$3::VARCHAR2(25),$4::VARCHAR2(25),$5::VARCHAR2(20),$6::DATE,$7::VARCHAR2(10),$8::NUMBER(8,2),$9::NUMBER(2,2),$10::NUMBER(6),$11::NUMBER(4)
		,MD5($2||$3||$4||$5||DATE($6)::VARCHAR2(10)||$7||$8::VARCHAR2(10)||$9::VARCHAR2(4)||$10::VARCHAR2(6)||$11::VARCHAR2(4)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_EMPLOYEES_DATA);
		 
--JOB_HISTORY LOAD 

COPY INTO EDW.EDW_STG.JOB_HISTORY
    FROM
        (SELECT $1::NUMBER(6),$2::DATE,$3::DATE,$4::VARCHAR2(10),$5::NUMBER(4),MD5(DATE($2)::VARCHAR2(10)||DATE($3)::VARCHAR2(10)||$4||$5::VARCHAR2(4)),'EDW'::VARCHAR2(32),CURRENT_TIMESTAMP::TIMESTAMP_NTZ,CURRENT_TIMESTAMP::TIMESTAMP_NTZ
         FROM @HR_JOB_HISTORY_DATA);